### ISSUE TITLE
Got error when create RS256 JWT

### ISSUE THREAD

**Issue by ekenli** [SP3269/posh-jwt#4]
#No error to create New-Object X509Certificate2
`$cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2("\131519.p12","notasecret") `

#Got error when create the RS256JWT
`$jwt = New-Jwt -Cert $cert -PayloadJson $payLoad  -Verbose`

Signing with SHA256 and Pkcs1 padding failed using private key 
System.Security.Cryptography.RSACryptoServiceProvider
At C:\Program Files\WindowsPowerShell\Modules\JWT\1.9.0\JWT.psm1:282 char:25
 ...     catch { throw "Signing with SHA256 and Pkcs1 padding failed using ...
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Signing with SH...ServiceProvider:String) [], RuntimeExcepti 
   on
    + FullyQualifiedErrorId : Signing with SHA256 and Pkcs1 padding failed using private key System.Security. 
   Cryptography.RSACryptoServiceProvider

**Comment by jlightfoot** [comment]
I was getting the same error.  Apparently, it had to do with the cryptographic service provider being used.  When I generated the pkcs12 cert normally with openssl, it used "Microsoft Enhanced Cryptographic Provider v1.0".  When I made the cert with the following openssl command, it forced using the proper CSP and started working:
openssl pkcs12 -export -CSP "Microsoft Enhanced RSA and AES Cryptographic Provider" -inkey yourprivkey.pem -in yourcert.pem -out yourcert.pfx

**Comment by jlightfoot** [comment]
> #No error to create New-Object X509Certificate2
> `$cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2("\131519.p12","notasecret") `
> 
> #Got error when create the RS256JWT
> `$jwt = New-Jwt -Cert $cert -PayloadJson $payLoad -Verbose`
> 
> Signing with SHA256 and Pkcs1 padding failed using private key
> System.Security.Cryptography.RSACryptoServiceProvider
> At C:\Program Files\WindowsPowerShell\Modules\JWT\1.9.0\JWT.psm1:282 char:25
> ... catch { throw "Signing with SHA256 and Pkcs1 padding failed using ...
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> + CategoryInfo : OperationStopped: (Signing with SH...ServiceProvider:String) [], RuntimeExcepti
> on
> + FullyQualifiedErrorId : Signing with SHA256 and Pkcs1 padding failed using private key System.Security.
> Cryptography.RSACryptoServiceProvider

I was getting the same error. Apparently, it had to do with the cryptographic service provider being used. When I generated the pkcs12 cert normally with openssl, it used "Microsoft Enhanced Cryptographic Provider v1.0". When I made the cert with the following openssl command, it forced using the proper CSP and started working:
openssl pkcs12 -export -CSP "Microsoft Enhanced RSA and AES Cryptographic Provider" -inkey yourprivkey.pem -in yourcert.pem -out yourcert.pfx

**Comment by SP3269** [comment]
A pull request - #3 - was merged to retain inner exception information in the thrown error. New version is published to PowerShell Gallery.

Closing this issue. Thank you, @jlightfoot, for the input
